const std = @import("std");
const testing = std.testing;

const zant = @import("zant");
const gasf = zant.TensorToImage.gasf.gasf;

test "GASF Reference Python Test" {
    const input = [_]f32{ 0.1, 0.5, -0.3, 0.8 };
    const n = input.len;
    
    // Expected output generated via pyts
    const expected = [_]u8{
        19, 2, 162, 93,
        2, 53, 70, 185,
        162, 70, 255, 0,
        93, 185, 0, 255,
    };
    
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    
    const result = try gasf(arena.allocator(), &input);
    
    try testing.expectEqual(@as(usize, n * n), result.len);
    
    // Check pixel-by-pixel match with Python reference
    for (expected, result) |exp, res| {
        // Allow ±1 tolerance for small floating point rounding differences
        const diff = if (exp > res) exp - res else res - exp;
        try testing.expect(diff <= 1);
    }
}

test "GASF Symmetry Property" {
    // A matrix generated by GASF should always be symmetric: G[i][j] == G[j][i].
    const input = [_]f32{ 1.0, 2.5, -1.0, 0.3, 0.8 };
    const n = input.len;
    
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    
    const result = try gasf(arena.allocator(), &input);
    
    for (0..n) |i| {
        for (0..n) |j| {
            try testing.expectEqual(result[i * n + j], result[j * n + i]);
        }
    }
}

test "GASF Flatline Edge Case" {
    // If input is perfectly flat, normalized values are 0.
    // G[i][j] = xi*xj - sqrt(1-xi^2)*sqrt(1-xj^2) = 0 - 1 = -1
    // Rescaled logic: (-1 + 1)/2 * 255 = 0
    const input = [_]f32{ 5.0, 5.0, 5.0, 5.0 };
    
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    
    const result = try gasf(arena.allocator(), &input);
    
    for (result) |pixel| {
        try testing.expectEqual(@as(u8, 0), pixel);
    }
}

test "GASF Diagonal Property" {
    // The main diagonal should map to: G[i][i] = 2*xi^2 - 1
    const input = [_]f32{ 0.1, 0.5, -0.3, 0.8 };
    const n = input.len;
    
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    
    // We need normalized values to check the math property against the results
    // Since we import zant, we don't have direct access to normalize_minmax here,
    // so we'll just test the resulting pixel logic mathematically given the normalization.
    const result = try gasf(arena.allocator(), &input);
    
    // min = -0.3, max = 0.8, range = 1.1
    // norm = (2x - 0.5) / 1.1
    // norm(0.1) = -0.2727
    // norm(0.5) = 0.4545
    // norm(-0.3) = -1.0
    // norm(0.8) = 1.0
    const expected_norms = [_]f32{ -0.272727, 0.454545, -1.0, 1.0 };
    
    for (0..n) |i| {
        const xi = expected_norms[i];
        const expected_g = 2.0 * xi * xi - 1.0;
        const expected_pixel = @as(u8, @intFromFloat(@round((expected_g + 1.0) / 2.0 * 255.0)));
        
        const diff = if (expected_pixel > result[i * n + i]) expected_pixel - result[i * n + i] else result[i * n + i] - expected_pixel;
        try testing.expect(diff <= 1);
    }
}

test "GASF Output Bounds" {
    // All pixels should be within [0, 255]
    // Since output type is u8, they are theoretically always in bounds, 
    // but this ensures no overflow crashes occurred and logic is sound.
    const input = [_]f32{ 1e5, 2e5, -1e5, 0.0 };
    
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    
    const result = try gasf(arena.allocator(), &input);
    
    for (result) |pixel| {
        try testing.expect(pixel >= 0 and pixel <= 255);
    }
}
