const std = @import("std");
const testing = std.testing;

const zant = @import("zant");
const gasf = zant.TensorToImage.gasf.gasf;
const lean_gasf = zant.TensorToImage.gasf.lean_gasf;

test "lean_gasf: caller-supplied cosines_buffer produces same result as standard wrapper" {
    // Verifies the zero-allocation core with explicit cosines buffer matches the standard path.
    const normalized = [_]f32{ -0.272727, 0.454545, -1.0, 1.0 };
    const n = normalized.len;

    var cosines_buf: [n]f32 = undefined;
    var output: [n * n]f32 = undefined;

    lean_gasf(&normalized, &cosines_buf, &output);

    // Expected: G[i][j] = xi*xj - sqrt(1-xi²)*sqrt(1-xj²)
    for (0..n) |i| {
        for (0..n) |j| {
            const xi = normalized[i];
            const xj = normalized[j];
            const sq_xi = @sqrt(@max(0.0, 1.0 - xi * xi));
            const sq_xj = @sqrt(@max(0.0, 1.0 - xj * xj));
            const expected = xi * xj - sq_xi * sq_xj;
            const diff = @abs(expected - output[i * n + j]);
            try testing.expect(diff <= 0.0001);
        }
    }
}

test "GASF Reference Python Test" {
    const input = [_]f32{ 0.1, 0.5, -0.3, 0.8 };
    const n = input.len;
    
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    
    const result = try gasf(arena.allocator(), &input, .MinusOneToOne);
    
    try testing.expectEqual(@as(usize, n * n), result.len);
    
    // Expected normalized values:
    const expected_norms = [_]f32{ -0.272727, 0.454545, -1.0, 1.0 };
    for (0..n) |i| {
        for (0..n) |j| {
            const xi = expected_norms[i];
            const xj = expected_norms[j];
            const sq_xi = @sqrt(@max(0.0, 1.0 - xi * xi));
            const sq_xj = @sqrt(@max(0.0, 1.0 - xj * xj));
            const expected_g = xi * xj - sq_xi * sq_xj;
            const res = result[i * n + j];
            const diff = if (expected_g > res) expected_g - res else res - expected_g;
            try testing.expect(diff <= 0.001);
        }
    }
}

test "GASF Symmetry Property" {
    // A matrix generated by GASF should always be symmetric: G[i][j] == G[j][i].
    const input = [_]f32{ 1.0, 2.5, -1.0, 0.3, 0.8 };
    const n = input.len;
    
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    
    const result = try gasf(arena.allocator(), &input, .MinusOneToOne);
    
    for (0..n) |i| {
        for (0..n) |j| {
            try testing.expectEqual(result[i * n + j], result[j * n + i]);
        }
    }
}

test "GASF Flatline Edge Case" {
    // If input is perfectly flat, minmax normalization sets values to 0.
    // G[i][j] = xi*xj - sqrt(1-xi^2)*sqrt(1-xj^2) = 0 - 1 = -1
    const input = [_]f32{ 5.0, 5.0, 5.0, 5.0 };
    
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    
    const result = try gasf(arena.allocator(), &input, .MinusOneToOne);
    
    for (result) |pixel| {
        try testing.expectEqual(@as(f32, -1.0), pixel);
    }
}

test "GASF Diagonal Property" {
    // The main diagonal should map to: G[i][i] = 2*xi^2 - 1
    const input = [_]f32{ 0.1, 0.5, -0.3, 0.8 };
    const n = input.len;
    
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    
    // We need normalized values to check the math property against the results
    const result = try gasf(arena.allocator(), &input, .MinusOneToOne);
    
    // min = -0.3, max = 0.8, range = 1.1
    // norm = (2x - 0.5) / 1.1
    const expected_norms = [_]f32{ -0.272727, 0.454545, -1.0, 1.0 };
    
    for (0..n) |i| {
        const xi = expected_norms[i];
        const expected_g = 2.0 * xi * xi - 1.0;
        
        const res = result[i * n + i];
        const diff = if (expected_g > res) expected_g - res else res - expected_g;
        try testing.expect(diff <= 0.001);
    }
}

test "GASF Output Bounds" {
    // All values should be within [-1.0, 1.0]
    const input = [_]f32{ 1e5, 2e5, -1e5, 0.0 };
    
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    
    const result = try gasf(arena.allocator(), &input, .MinusOneToOne);
    
    for (result) |val| {
        try testing.expect(val >= -1.0001 and val <= 1.0001);
    }
}
