name=Zant
version=1.0.0
author=AnonymousZanter <AnonymousZanter@zant.com>
maintainer=AnonymousZanter <AnonymousZanter@zant.com>
sentence= Static Cortex-M4 library.
paragraph= Library description
category=Uncategorized
url=https://zantfoundation.github.io/Website/

architectures=stm32,cortex-m4
precompiled=full
includes=lib_zant.h
precompiled=true
ldflags=-lzant