name=test1
version=1.0.0
author=Panizzi-Pellizzari-Polise
maintainer=Panizzi-Pellizzari-Polise
sentence= Static Cortex-M7 library.
paragraph= Library description
category=Uncategorized
architectures=mbed_nicla
precompiled=full
includes=lib_zant.h
precompiled=true
ldflags=-lzant