name: Z-Ant base tests

on:
  push:
    branches: [feat/cicd]
  workflow_dispatch:

jobs:
  setup-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.15.2 # Current zig version supported by the library
    
      - name: run general zig tests
        run: zig build test --summary all